---
title: "S4th_correlationTo_SArank_SA12sumSCinvnode_HCPD"
author: "Xiaoyu xu"
date: "5/15/2024"
output: html_document
---
This script is to conduct correlation analysis between gam statistical indexes to connectional axis rank. And draw scatter plots & matrix graphs.
Spearman correlations were conducted.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(R.matlab)
library(tidyverse)
library(parallel)
library(psych)
library(corrplot)
library(reshape)
rm(list = ls())
demopath<-'D:/xuxiaoyu/DMRI_network_development/SC_development/demopath'
functionFolder<-'D:/xuxiaoyu/DMRI_network_development/SC_development/Rcode_SCdevelopment/gamfunction'
resultFolder<-'D:/xuxiaoyu/DMRI_network_development/SC_development/results'
interfileFolder <- 'D:/xuxiaoyu/DMRI_network_development/SC_development/interdataFolder_HCPD'
FigureFolder<-'D:/xuxiaoyu/DMRI_network_development/SC_development/Figure_HCPD_final/SA12'

```

## 1. data prepare

```{r prepare_data}
#### load data
CVthr = 75
gamresult<-readRDS(paste0(interfileFolder, '/gamresults78_sumSCinvnode_over8_CV', CVthr,'_scale_TRUE.rds'))
gamresult$pfdr <- p.adjust(gamresult$anova.smooth.pvalue, method="fdr")
gamresult$sig <- (gamresult$pfdr < 0.05) # CV25 56 sig edges CV75 70 sig edges
print(paste0(sum(gamresult$sig), " edges have significant developmental effects."))
SCdata <- readRDS(paste0(interfileFolder, '/SCdata_SA12_CV', CVthr,'_sumSCinvnode.sum.msmtcsd.merge.rds'))
EuricDistance <- read.csv(paste0(interfileFolder, "/average_EuclideanDistance_12.csv"))
#### source function
source(paste0(functionFolder, '/SCrankcorr.R'))
source('D:/xuxiaoyu/DMRI_network_development/Normative_model/functions/plotmatrix.R')

meanSC <- colMeans(SCdata[,which(str_detect(names(SCdata), "SC."))])
meandistance <- colMeans(SCdata[,which(str_detect(names(SCdata), "distance"))])

#### convert critical ages of insignificantly developmental edges to NA
#### convert critical ages equal to age boundaries to NA
gamresult$EuricDistance <- EuricDistance$Edistance
gamresult$increase.onset[gamresult$sig==FALSE]<-NA ; gamresult$increase.onset2 <- gamresult$increase.onset
gamresult$increase.onset2[round(gamresult$increase.onset2,2)==8.08] <- NA
gamresult$increase.offset[gamresult$sig==FALSE]<-NA ; gamresult$increase.offset2 <- gamresult$increase.offset
gamresult$increase.offset2[round(gamresult$increase.offset2,2)==21.92] <- NA
gamresult$peak.change[gamresult$sig==FALSE]<-NA
gamresult$peak.increase.change[gamresult$sig==FALSE]<-NA
gamresult$pfdr <- p.adjust(gamresult$anova.smooth.pvalue, method = "fdr")

```

## 1. compute correlations to SC rank

```{r corr_SCrank}
gamresult <- gamresult %>% mutate(meanderv2_c = case_when(
  meanderv2 < mean(meanderv2)-3*sd(meanderv2) ~ NA,
  .default = meanderv2
))

computevar.list <- c("partialRsq", "increase.onset2", "increase.offset2", "peak.increase.change",
                     "meanderv2_c")
for (x in 1:5){
  computevar <- computevar.list[x]
  ds.resolution<-12
  correlation.df <- SCrankcorr(gamresult, computevar, ds.resolution, dsdata=FALSE)
  if (x==1){
    SCrank_correlation <- correlation.df
  }else{
    SCrank_correlation <- rbind(SCrank_correlation, correlation.df)
  }
}
SCrank_correlation

## 1.1 Validation: Control for Euclidean distance
#corr.test(gamresult$partialRsq, gamresult$EuricDistance, method = "pearson")
#corr.test(gamresult$meanderv2, gamresult$EuricDistance, method = "pearson")
meanderv2_control_distance <- residuals(lm(meanderv2_c~EuricDistance, data=gamresult))
#corr.test(meanderv2_control_distance, gamresult$EuricDistance, method = "pearson") # r=0
gamresult$meanderv2_control_distance[!is.na(gamresult$meanderv2_c)] <- meanderv2_control_distance
SCrankcorr(gamresult, "meanderv2_control_distance", 12, dsdata=FALSE)
partialRsq_control_distance <- residuals(lm(partialRsq~EuricDistance, data=gamresult))
#corr.test(partialRsq_control_distance, gamresult$EuricDistance, method = "pearson") # r=0
gamresult$partialRsq_control_distance <- partialRsq_control_distance
SCrankcorr(gamresult, "partialRsq_control_distance", 12, dsdata=FALSE)

```
## 2. scatter plots

```{r scatter_plot}
# meanderv2
computevar <- "meanderv2_c"
correlation.df <- SCrankcorr(gamresult, computevar, ds.resolution,dsdata=TRUE)
mtrixplot <- matrix(NA, ds.resolution, ds.resolution)
mtrixplot[lower.tri(mtrixplot, diag = T)] <- correlation.df$meanderv2
mytheme <- theme(axis.text=element_text(size=20, color="black"), 
                 axis.title =element_text(size=20),aspect.ratio = 0.95,
                 axis.line = element_line(linewidth=0.6),axis.ticks= element_line(linewidth=0.6),
                 plot.title = element_text(size=20, hjust = 0.5, vjust=2),
                 plot.background=element_rect(fill="transparent"),
                 panel.background=element_rect(fill="transparent"),
                 legend.position = "none")
width =17.5; height = 15


ggplot(data=correlation.df)+
  geom_point(aes(x=SCrank, y=meanderv2_c, color=SCrank), size=5)+
  geom_smooth(aes(x=SCrank, y=meanderv2_c),linewidth=2, method ="lm", color="black")+
  scale_color_distiller(type="seq", palette = "RdBu", direction = -1)+
  labs(x="S-A connectional axis rank", y="Second derivative")+
  scale_y_continuous(breaks = c(-0.002, 0, 0.002), labels = c(-2, 0, 2))+
  theme_classic()+mytheme


ggsave(paste0(FigureFolder,'/CV', CVthr, '/correlation_sumSCinvnode_SCrank/mean', computevar, '_SCrankcorr_n', ds.resolution, '.tiff'), width=17, height =14, units = "cm")
ggsave(paste0(FigureFolder,'/CV', CVthr, '/correlation_sumSCinvnode_SCrank/mean', computevar, '_SCrankcorr_n', ds.resolution, '.svg'), dpi=600, width=width, height =height, units = "cm")

# meanderv2_controldistance
computevar <- "meanderv2_control_distance"
correlation.df <- SCrankcorr(gamresult,computevar, ds.resolution,dsdata=TRUE)
mtrixplot <- matrix(NA, ds.resolution, ds.resolution)
mtrixplot[lower.tri(mtrixplot, diag = T)] <- correlation.df$meanderv2_control_distance
ggplot(data=correlation.df)+
  geom_point(aes(x=SCrank, y=meanderv2_control_distance, color=SCrank), size=5.2)+
  geom_smooth(aes(x=SCrank, y=meanderv2_control_distance),linewidth=1.2, method ="lm", color="black")+
  scale_color_distiller(type="seq", palette = "RdBu",direction = -1)+
  labs(x="S-A connectional axis rank", y="Second derivative")+
  scale_y_continuous(breaks = c(-0.002, 0, 0.002), labels=c(-2, 0, 2))+
  theme_classic()+
  theme(axis.text=element_text(size=23, color="black"), 
        axis.title =element_text(size=23),aspect.ratio = 0.9,
        axis.line = element_line(linewidth=0.6),axis.ticks= element_line(linewidth=0.6),
        plot.title = element_text(size=20, hjust = 0.5, vjust=2),
        plot.background=element_rect(fill="transparent"),
        panel.background=element_rect(fill="transparent"),
        legend.position = "none")
ggsave(paste0(FigureFolder,'/CV', CVthr, '/correlation_sumSCinvnode_SCrank/mean', computevar, '_SCrankcorr_n', ds.resolution, '.tiff'), width=13, height =12, units = "cm")
ggsave(paste0(FigureFolder,'/CV', CVthr, '/correlation_sumSCinvnode_SCrank/mean', computevar, '_SCrankcorr_n', ds.resolution, '.svg'), dpi=600, width=16, height =14, units = "cm")

```

## 3. matrix graphs for resolution of 12

```{r matrix_graph, eval=FALSE}

# partial Rsq
partialRsq <- plotmatrix(dataname = "gamresult", variable="partialRsq", ds.resolution=12, Pvar="pfdr", NAcol="white", lmthr=NA, axeslabels=NULL, axeslabelsGap=T, linerange_frame=NA, PaletteSet=NA)
partialRsq
ggsave(paste0(FigureFolder, "/CV", CVthr, "/Matrix12_sumSCinvnode_gamstats_Age8_22/partialRsq_", ds.resolution, "net_delLM_CV75.tiff"), partialRsq, width = 18, height = 16, units = "cm")
# Mean 2nd derivative
meanderv2_c <- plotmatrix(dataname = "gamresult", variable="meanderv2_c", ds.resolution=12, Pvar=NA, NAcol="#053061", lmthr=NA, axeslabels=NULL, axeslabelsGap=T, linerange_frame=NA, PaletteSet=NA)
meanderv2_c
ggsave(paste0(FigureFolder, "/CV", CVthr, "/Matrix12_sumSCinvnode_gamstats_Age8_22/meanderv2_c_", ds.resolution, "net_delLM_CV75.tiff"), meanderv2_c, width = 18, height = 16, units = "cm")
# Mean 2nd derivative while controlling distance
meanderv2_control_distance <- plotmatrix(dataname = "gamresult", variable="meanderv2_control_distance", ds.resolution=12, Pvar=NA, NAcol="#053061", lmthr=NA, axeslabels=NULL, axeslabelsGap=T, linerange_frame=NA, PaletteSet=NA)
meanderv2_control_distance
ggsave(paste0(FigureFolder, "/CV", CVthr, "/Matrix12_sumSCinvnode_gamstats_Age8_22/meanderv2_control_distance_", ds.resolution, "net_delLM_CV75.tiff"), meanderv2_control_distance, width = 18, height = 16, units = "cm")


```



