---
title: "S1st_testCog_correlation_wholesample_ABCD"
author: "Xiaoyu xu"
date: "4/17/2024"
output: html_document
---
This script is to calculate associations between fluid cognition and SC strength in the ABCD dataset. GAM models were used to regress covariates. Statistical indices will be generated.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mgcv)
library(parallel)
library(psych)
library(reshape)
library(RColorBrewer)
library(tidyverse)
rm(list = ls())
CVthr=75
wdpath <- getwd()
if (str_detect(wdpath, "ibmgpfs")){
  resultFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SC_development/results_ABCD'
  interfileFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SC_development/interdataFolder_ABCD'
  functionFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SC_development/Rcode_SCdevelopment/gamfunction'

}else{
  resultFolder <- 'D:/xuxiaoyu/DMRI_network_development/SC_development/results_ABCD'
  interfileFolder <- 'D:/xuxiaoyu/DMRI_network_development/SC_development/interdataFolder_ABCD'
  functionFolder<-'D:/xuxiaoyu/DMRI_network_development/SC_development/Rcode_SCdevelopment/gamfunction'
  FigureFolder<-paste0('D:/xuxiaoyu/DMRI_network_development/SC_development/Figure_ABCD_final/SA12/CV', CVthr)
  
}
# load data
SCdata<-readRDS(paste0(interfileFolder, '/SCdata_SA12_CV75_sumSCinvnode.sum.msmtcsd.combatgam_neuroharmonize_cognition.rds'))
meandistance <- read.csv(paste0(interfileFolder, "/average_EuclideanDistance_12.csv"))
meandistance <- meandistance$Edistance

# source function
source(paste0(functionFolder, "/gamcog.R"))
source(paste0(functionFolder, "/SCrankcorr.R"))

```

## 1. Cognition association
Fluid cognition is only measured at baseline, GAM model was used
```{r cog_corr}
Cogvar <- "nihtbx_fluidcomp_uncorrected"

summary(SCdata[,Cogvar])
nonna_index<-which(!is.na(SCdata[ ,Cogvar]))
SCdata.cog<-SCdata[nonna_index,]
SCdata.cog$eventname <- str_split_i(SCdata.cog$scanID, "ses-", 2)
SCdata.cog <- SCdata.cog[SCdata.cog$eventname=="baselineYear1Arm1",]
cogagemodel <- gam(nihtbx_fluidcomp_uncorrected~s(age,k=3, fx=TRUE)+sex+mean_fd, data=SCdata.cog)
t <- summary(cogagemodel)
print(paste("age, sex, mean_fd can explain", round(t$r.sq, 3), "variance of cognition.")) # 0.083
dataname<-"SCdata.cog"
smooth_var<-"age"
covariates<-"sex+mean_fd"
knots<-3
corrmethod<-"pearson"

rerun <- F
# fit model
if (rerun==T){
  resultsum <- mclapply(1:78, function(x) {
    SClabel <- grep("SC.", names(SCdata), value=T)[x]
    region <- SClabel
    gamresult <-gam.fit.cognition(region, dataname, Cogvar, smooth_var, covariates, knots, set_fx = T, stats_only = T)
    #gamresult <- as.data.frame(gamresult[[1]])
    return(gamresult)
  }, mc.cores = 50)
  SC_Cog_results.df <- do.call(rbind, lapply(resultsum, function(x) data.frame(x)))
  SC_Cog_results.df[,c(3:10)]<-lapply(SC_Cog_results.df[,c(3:10)], as.numeric)
  SC_Cog_results.df$corr.p.fdr<-p.adjust(SC_Cog_results.df$corrp, method="fdr")
  SC_Cog_results.df$anova.cov.p.fdr<-p.adjust(SC_Cog_results.df$anova.cov.pvalue, method="fdr")
  SC_Cog_results.df$gam.smooth.p.fdr<-p.adjust(SC_Cog_results.df$gam.cog.pvalue, method="fdr")
  summary(SC_Cog_results.df)
  SC_Cog_results.df$parcel[which.min(SC_Cog_results.df$gam.cog.t)] # SC.72
  saveRDS(SC_Cog_results.df, paste0(interfileFolder, "/SC_Cog_results_", Cogvar,"_CV", CVthr,"_cog2SC.rds"))
  length(SC_Cog_results.df$parcel[SC_Cog_results.df$anova.cov.p.fdr<0.05])}else{
    SC_Cog_results.df <- readRDS(paste0(interfileFolder, "/SC_Cog_results_", Cogvar,"_CV", CVthr,"_cog2SC.rds"))
  }
print(paste(sum(SC_Cog_results.df$anova.cov.p.fdr < 0.05), "edges have significant associations with ", Cogvar," cognition."))
SC_Cog_results.df.whole <- SC_Cog_results.df
SCrankresult.whole<-SCrankcorr(SC_Cog_results.df.whole,"gam.cog.t", 12)
print(paste("Correlation coefficient between cognitve associations and connectional axis is", round(SCrankresult.whole$r.spearman,2), "with a P value of", round(SCrankresult.whole$p.spearman,3)))
print(SCrankresult.whole)


```

## 2. Plot: scatter plot+matrix graph

```{r plot}
correlation.df <- SCrankcorr(SC_Cog_results.df, "gam.cog.t", 12,dsdata=TRUE)
correlation.df$sig <- (SC_Cog_results.df$anova.cov.p.fdr<0.05)
Matrix.tmp <- matrix(NA, nrow = 12, ncol=12)
linerange_frame<-data.frame(x=c(0.5,12+0.5), ymin =rep(-12-0.5, times=2), ymax =rep(-0.5, times=2),
                            y=c(-0.5, -12-0.5), xmin=rep(0.5, times=2), xmax=rep(12+0.5, times=2))
SC_Cog_results.tmp <-SC_Cog_results.df.whole
SC_Cog_results.tmp$SCrank <- correlation.df$SCrank

lwth <- min(SC_Cog_results.tmp$gam.cog.t)

mytheme<-theme(axis.text=element_text(size=23.2, color="black"), 
               axis.title =element_text(size=23.2),aspect.ratio = 0.88,axis.line = element_line(linewidth = 0.6),
               axis.ticks = element_line(linewidth = 0.6),
               plot.title = element_text(size=15, hjust = 0.5, vjust=0),
               plot.subtitle = element_text(size=15, hjust = 0.9, vjust=-6),
               plot.background=element_rect(fill="transparent"),
               panel.background=element_rect(fill="transparent"),plot.margin = margin(t=10,r=5,b=5,l=5, unit="pt"),
               legend.position = "none")


Fig <- ggplot(data=SC_Cog_results.tmp)+
  geom_point(aes(x=SCrank, y=gam.cog.t, color=gam.cog.t), size=5.5)+
  geom_smooth(aes(x=SCrank, y=gam.cog.t), method ="lm", color="black", linewidth=1.4)+
  scale_colour_distiller(type="seq", palette = "RdBu",limits=c(lwth, -lwth), direction = -1)+
  labs(x="S-A connectional axis rank", y=expression("Cognitive association ("*italic("T")*" value)"))+
  theme_classic()+mytheme
  
Fig
ggsave(paste0(FigureFolder, '/cognition/', Cogvar, '/CorrTvalue_SCrankcorr_n12_siteall.tiff'), Fig, width=16.5, height =16, units = "cm")


Matrix.tmp.T <- Matrix.tmp
Matrix.tmp.T[lower.tri(Matrix.tmp.T, diag = T)] <- SC_Cog_results.tmp$gam.cog.t
Matrix.tmp.T[upper.tri(Matrix.tmp.T)] <- t(Matrix.tmp.T)[upper.tri(Matrix.tmp.T)]
colnames(Matrix.tmp.T) <-seq(1, 12)
rownames(Matrix.tmp.T) <-seq(1, 12)
matrixtmp.df <- as.data.frame(Matrix.tmp.T)
matrixtmp.df$nodeid <- seq(1, 12)
matrixtmp.df.melt <- melt(matrixtmp.df,id.vars=c("nodeid"))
matrixtmp.df.melt$variable<-as.numeric(matrixtmp.df.melt$variable)
matrixtmp.df.melt$nodeid<-0-matrixtmp.df.melt$nodeid
matrixtmp.df.melt$value<-as.numeric(matrixtmp.df.melt$value)

Matrix.tmp.sig <- Matrix.tmp
Matrix.tmp.sig[lower.tri(Matrix.tmp.sig, diag = T)] <- correlation.df$sig
Matrix.tmp.sig[upper.tri(Matrix.tmp.sig)] <- t(Matrix.tmp.sig)[upper.tri(Matrix.tmp.sig)]
colnames(Matrix.tmp.sig) <-seq(1, 12)
rownames(Matrix.tmp.sig) <-seq(1, 12)
matrixtmp.df.sig <- as.data.frame(Matrix.tmp.sig)
matrixtmp.df.sig$nodeid <- seq(1, 12)
matrixtmp.df.sig.melt <- melt(matrixtmp.df.sig,id.vars=c("nodeid"))
matrixtmp.df.sig.melt$variable<-as.numeric(matrixtmp.df.sig.melt$variable)
matrixtmp.df.sig.melt$nodeid<-0-matrixtmp.df.sig.melt$nodeid
matrixtmp.df.sig.melt$value<-as.numeric(matrixtmp.df.sig.melt$value)
matrixtmp.df.sig.melt <- matrixtmp.df.sig.melt[-which(matrixtmp.df.sig.melt$value==0),]
titlematrix <- Cogvar
Fig<-ggplot(data =matrixtmp.df.melt)+
  geom_tile(aes(x=variable, y=nodeid, fill = value, color=value))+
  scale_fill_distiller(type="seq", palette = "RdBu",limits=c(lwth, -lwth),na.value = "grey")+
  scale_color_distiller(type="seq", palette = "RdBu",limits=c(lwth, -lwth),na.value = "grey")+
  geom_text(data =matrixtmp.df.sig.melt, aes(x=variable, y=nodeid, label = "*"), vjust = 0.7, hjust = 0.5, size=8)+
  geom_linerange(data=linerange_frame, aes(y=y, xmin =xmin, xmax =xmax), color="black", linewidth=0.5)+
  geom_linerange(data=linerange_frame, aes(x=x, ymin =ymin, ymax =ymax), color="black", linewidth=0.5)+
  geom_segment(aes(x = 0.5 , y = -0.5 , xend = 12+0.5 ,yend = -12-0.5), color="black", linewidth=0.5)+
  ggtitle(label = titlematrix)+labs(x=NULL, y=NULL)+
  scale_y_continuous(breaks=NULL, labels = NULL)+
  scale_x_continuous(breaks=NULL, labels = NULL)+
  theme(axis.line = element_blank(),
        #axis.ticks=element_line(linewidth = 0),
        axis.text.x=element_text(size=12, angle=45, hjust=1),
        axis.text.y=element_text(size=12, angle=315, hjust=1,vjust=1),
        axis.title =element_text(size=18),
        plot.title = element_text(size=12, hjust = 0.5),
        legend.title=element_text(size=18),
        legend.text=element_text(size=18),
        panel.background=element_rect(fill=NA),
        panel.grid.major=element_line(linewidth = 0),
        panel.grid.minor=element_line(linewidth = 1))
Fig
filename<-paste0(FigureFolder, '/cognition/', Cogvar, '/CorrTvalue_Matrix_n12_siteall.tiff')
ggsave(filename, Fig,  height = 15, width = 16, units = "cm")



```


