---
title: "S1st_testCog_correlation_wholesample_HCPD"
author: "Xiaoyu xu"
date: "4/17/2024"
output: html_document
---
This script is to calculate associations between fluid cognition and SC strength in the HCP-D dataset. GAM models were used to regress covariates. Statistical indexes will be generated.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mgcv)
library(parallel)
library(psych)
library(reshape)
library(tidyverse)
rm(list = ls())
CVthr=75
wdpath <- getwd()
if (str_detect(wdpath, "Users")){
resultFolder <- '/Users/xuxiaoyu_work/Cuilab/DMRI_network_development/SC_development/results'
interfileFolder <- '/Users/xuxiaoyu_work/Cuilab/DMRI_network_development/SC_development/interdataFolder_HCPD'
functionFolder<-'/Users/xuxiaoyu_work/Cuilab/DMRI_network_development/SC_development/Rcode_SCdevelopment/gamfunction'
FigureFolder<-paste0('/Users/xuxiaoyu_work/Cuilab/DMRI_network_development/SC_development/Figure_HCPD_final/SA12/CV',CVthr)
  source(paste0(functionFolder, "/SCrankcorr_beforegam.R"))
  perm.id.full<-readRDS("/Users/xuxiaoyu_work/Cuilab/GeneralRfunctions/rotate_parcellation/SA12_sphericalrotations_N10000.rds")
  
}else if (str_detect(wdpath, "cuizaixu_lab")){
  interfileFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/interdataFolder_HCPD'
  functionFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/Rcode_SCdevelopment/gamfunction'
  resultFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/results_HCPD'
}
# load data
SCdata<-readRDS(paste0(interfileFolder, '/SCdata_SA12_CV', CVthr,'_sumSCinvnode.sum.msmtcsd.combatNTBfluid.rds'))
gamresultsum<-readRDS(paste0(interfileFolder, '/gamresults78_sumSCinvnode_over8_CV', CVthr,'.rds'))
# source function
source(paste0(functionFolder, "/gamcog.R"))
source(paste0(functionFolder, '/colorbarvalue.R'))
source(paste0(functionFolder, "/plotdata_generate.R"))
# age can explain 49.7 % variance of cognition
cogagemodel <- gam(Ntb_fluid_uncor~s(age,k=3, fx=TRUE)+gender+handnessfactor+race+mean_fd, data=SCdata)
t <- summary(cogagemodel)
print(paste("age can explain", round(t$r.sq, 3), "variance of cognition."))
```

## 1. Cognition correlation
```{r Cog_corr}
Cogvar <- "Ntb_fluid_uncor"
dataname<-"SCdata"
smooth_var<-"age"
covariates<-"gender+handnessfactor+race+mean_fd"
knots<-3
corrmethod<-"pearson"
# fit model
if (str_detect(wdpath, "cuizaixu")){
  resultsum <- mclapply(1:78, function(x) {
  SClabel <- names(SCdata)[x+1]
  region <- SClabel
  gamresult <-
    gam.fit.cognition(
      Cogvar,
      dataname,
      region, 
      smooth_var, 
      covariates, 
      knots,
      corrmethod, set_fx = TRUE, stats_only = TRUE
    )
  gamresult <- as.data.frame(gamresult)
  return(gamresult)
}, mc.cores = 40)
  SC_Cog_results.df <- do.call(rbind, lapply(resultsum, function(x) data.frame(x)))
SC_Cog_results.df[,c(3:10)]<-lapply(SC_Cog_results.df[,c(3:10)], as.numeric)
SC_Cog_results.df$anova.cov.p.fdr<-p.adjust(SC_Cog_results.df$anova.cov.pvalue, method="fdr")
saveRDS(SC_Cog_results.df, paste0(interfileFolder, "/gamresult_cognition_CV", CVthr, "_SA12.rds"))
}else{
  SC_Cog_results.df <- readRDS(paste0(interfileFolder, "/gamresult_cognition_CV", CVthr, "_SA12.rds"))
}
for (i in 1){
  print(paste(sum(SC_Cog_results.df$anova.cov.p.fdr < 0.05), "edges have significant associations with fluid cognition."))
print("No further analysis.")
}

```
