---
title: "S3rd_SCdev_vary_by_cognition_ABCD"
author: "Xiaoyu xu"
date: "3/21/2024"
output: html_document
---
This script depicts developmental trajectories vary by baseline cognition levels.
The developmental trajectories within deciles were averaged for visualization. Figure 6e.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mgcv)
library(parallel)
library(psych)
library(gratia)
library(tidyverse)
library(reshape)
library(RColorBrewer)
rm(list = ls())
CVthr=75
wdpath <- getwd()
if (str_detect(wdpath, "Users")){
  resultFolder <- '/Users/xuxiaoyu_work/Cuilab/DMRI_network_development/SC_development/results_ABCD'
  interfileFolder <- '/Users/xuxiaoyu_work/Cuilab/DMRI_network_development/SC_development/interdataFolder_ABCD'
  functionFolder<-'/Users/xuxiaoyu_work/Cuilab/DMRI_network_development/SC_development/Rcode_SCdevelopment/gamfunction'
  FigureFolder<-paste0('/Users/xuxiaoyu_work/Cuilab/DMRI_network_development/SC_development/Figure_ABCD_final/SA12/CV', CVthr)
  source(paste0(functionFolder, "/SCrankcorr.R"))
  perm.id.full<-readRDS("/Users/xuxiaoyu_work/Cuilab/GeneralRfunctions/rotate_parcellation/SA12_sphericalrotations_N10000.rds")
  
}else if (str_detect(wdpath, "cuizaixu_lab")){
  resultFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/results_ABCD'
  interfileFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/interdataFolder_ABCD'
  functionFolder <- '/ibmgpfs/cuizaixu_lab/xuxiaoyu/SCdevelopment/Rcode_SCdevelopment/gamfunction'
}
# load data
SA12_10 <- read.csv(paste0(interfileFolder, "/SA12_10.csv"))
plotdata <- readRDS(paste0(interfileFolder, '/plotdatasum.df_SA12_sumSCinvnode_siteall_CV', CVthr,'.rds'))
SCdata<-readRDS(paste0(interfileFolder, '/SCdata_SA12_CV', CVthr,'_sumSCinvnode.sum.msmtcsd.combatage.rds'))
Cogdf <- SCdata %>% select(subID, eventname, nihtbx_fluidcomp_uncorrected) %>% drop_na() %>% 
  filter(str_detect(eventname, "base"))
Cogdf <- reshape::rename(Cogdf, c(nihtbx_fluidcomp_uncorrected="nihtbx_fluidcomp_uncorrected_base"))
Cogdf$eventname <- NULL
SCdata <- SCdata %>% left_join(Cogdf, by="subID")
SCdata[,c("gender", "race", "handness")] <- lapply(SCdata[,c("gender", "race", "handness")], as.factor)
SCdata.diw <- SCdata
for (x in 1:78){
  region <- grep("SC.", names(SCdata), value = T)[x]
  plotdata.tmp <- plotdata[plotdata$SC_label==paste0("SC.", x, "_h"), ]
  SCstrength.diw <- SCdata[,region] / plotdata.tmp$fit[1]
  SCdata.diw[,region] <- SCstrength.diw
}
SCdata.diw[,grep("SC.", names(SCdata), value = T)] <- lapply(SCdata.diw[,grep("SC.", names(SCdata), value = T)], as.numeric)
SCdata.diw[,c("gender", "race", "handness")] <- lapply(SCdata.diw[,c("gender", "race", "handness")], as.factor)

# source function
source(paste0(functionFolder, "/gamminteraction.R"))
source(paste0(functionFolder, '/colorbarvalue.R'))
source(paste0(functionFolder, "/SCrankcorr_beforegam.R"))
perm.id.full<-readRDS("/Users/xuxiaoyu_work/Cuilab/GeneralRfunctions/rotate_parcellation/SA12_sphericalrotations_N10000.rds")
detectCores()
## SC rank
df <- data.frame(randommuber=rnorm(78))
df.SCrank12 <- SCrankcorr(df, "randommuber", 12, perm.id.full, dsdata=TRUE)
df.SCrank12$randommuber <- NULL

```

## 1. Generate plot data from interaction models.
Fitted values were generated using the interaction models and then averaged into 10 deciles at each age point.
```{r interaction}
Cogvar <- "nihtbx_fluidcomp_uncorrected_base"
dataname <- "SCdata.diw"; smooth_var<-"age"; int_var <- Cogvar
int_var.predict.percentile <- 0.1; covariates <- "gender+handness+race+mean_fd"
knots=3; set_fx = TRUE; increments = 1000

## plot data
if (str_detect(wdpath, "cuizaixu_lab")){
resultsum <- mclapply(1:78, function(x){
  SClabel <- grep("SC.", names(SCdata), value=T)[x]
  region <- SClabel
  int_var.predict.percentile <- 0.1
  plotdf.low <-gamm.smooth.predict.covariateinteraction(region, dataname, smooth_var, int_var,int_var.predict.percentile, covariates, knots, set_fx, increments, stats_only=F)
  plotdf.low <- plotdf.low[[2]]
  plotdf.low$label <- region
  plotdf.low$cognitionlevel <- "low"

  int_var.predict.percentile <- 0.9
  plotdf.high <-gamm.smooth.predict.covariateinteraction(region, dataname, smooth_var, int_var,int_var.predict.percentile, covariates, knots, set_fx, increments, stats_only=F)
  plotdf.high <- plotdf.high[[2]]
  plotdf.high$label <- region
  plotdf.high$cognitionlevel <- "high"

  plotdf <- rbind(plotdf.low, plotdf.high)
  return(plotdf)
}, mc.cores = 3)
saveRDS(resultsum, paste0(interfileFolder, '/plotdata_high90_low10_', Cogvar, '_develop.rds'))}else{
  resultsum <- readRDS(paste0(interfileFolder, '/plotdata_high90_low10_', Cogvar, '_develop.rds'))
}

plotdf <- do.call(rbind, resultsum)
plotdf <- merge(plotdf, SA12_10, by.x = "label", by.y = "SC_label")
plotdf.decile.low <- plotdf %>% filter(cognitionlevel=="low") %>% 
  group_by(decile, age) %>%
  summarise(fit.avg = mean(fitted), decile=mean(decile))
plotdf.decile.low$cognitionlevel <- "low"

plotdf.decile.high <- plotdf %>% filter(cognitionlevel=="high") %>% 
  group_by(decile, age) %>%
  summarise(fit.avg = mean(fitted), decile=mean(decile))
plotdf.decile.high$cognitionlevel <- "high"
plotdf.decile <- rbind(plotdf.decile.low, plotdf.decile.high)

```

## 2. Plots
Figure 6e.
```{r plots}
colorid <- rev(brewer.pal(10, "RdBu"))
for (i in 1:10){
  plotdf.tmp <- plotdf.decile[plotdf.decile$decile==i,]
  colorindex <- colorid[i]
  if (i == 1){
    mytheme=theme(axis.text=element_text(size=21, color="black"), 
        axis.title =element_text(size=21),aspect.ratio = 1,
        axis.line = element_line(linewidth=0.5),axis.ticks = element_line(linewidth=0.5),
        plot.background=element_rect(fill="transparent"),
        panel.border = element_rect(fill=NA, color="transparent"),
        panel.background=element_rect(fill="transparent", color="transparent"), legend.position = "none")

  }else{
    mytheme=theme(axis.text.x =element_text(size=21, color="black"), 
                  axis.text.y =element_text(size=21, color="transparent"),
        axis.title.x =element_text(size=21),
        axis.title.y =element_text(size=21, colour = "transparent"),
        aspect.ratio = 1,
        axis.line.x = element_line(linewidth=0.5), 
        axis.line.y = element_line(linewidth=0.5, colour = "transparent"),
        axis.ticks.x = element_line(linewidth=0.5),
        axis.ticks.y = element_line(linewidth=0.5, colour = "transparent"),
        plot.background=element_rect(fill="transparent"),
        panel.grid=element_line(linewidth=0.5, colour = "transparent"),
        panel.border = element_rect(fill=NA, color="transparent"),
        panel.background=element_rect(fill="transparent", color="transparent"), legend.position = "none")

  }
  
  
  Fig <- ggplot(data=plotdf.tmp)+
    geom_line(aes(x=age, y=fit.avg, group=cognitionlevel, linetype=cognitionlevel), linewidth=1.2, color=colorindex)+
    scale_linetype_manual(values=c("solid", "dashed"))+
    scale_y_continuous(breaks = c(0.9, 1.0, 1.1), limits=c(0.8997, 1.0980))+
    labs(x=NULL, y="SC strength (ratio)", color="Cognition")+
    mytheme
  
  Fig
  ggsave(paste0(FigureFolder, '/cognition/', Cogvar, '/Interaction/developmentcurve_decile', i, '.tiff'),Fig, width = 10, height = 10, units = "cm")
  ggsave(paste0(FigureFolder, '/cognition/', Cogvar, '/Interaction/developmentcurve_decile', i, '.svg'),Fig, width = 10, height = 10, units = "cm")
}

# Draw 10 decile lines separately for 2 levels of cognition
# low
ggplot(data=plotdf.decile.low, aes(x=age, y=fit.avg, group=decile, color=decile))+
  geom_line(size=1.5, alpha=0.8, linetype="dashed")+
  #paletteer::scale_color_paletteer_c("pals::ocean.matter", direction = -1, values=colorbarvalues.meanderiv2, oob = squish) +
  scale_color_distiller(type="seq", palette = "RdBu", direction = -1)+
  labs(x="Age (years)", y="SC strength (ratio)")+
  #scale_color_manual(values = rev(brewer.pal(6, "RdBu")))+
  theme_classic()+
  theme(axis.text=element_text(size=20, color="black"), 
        axis.title =element_text(size=20, color="black"),aspect.ratio = 0.8,
        plot.background=element_rect(fill="transparent"),legend.position = "none",
        panel.background=element_rect(fill="transparent"),
        plot.title = element_text(size=15, hjust = 0.5))
ggsave(paste0(FigureFolder, '/cognition/', Cogvar, '/Interaction/developmentcurve_decile_ratio_low.tiff'),width = 14, height = 12, units = "cm")
ggsave(paste0(FigureFolder, '/cognition/', Cogvar, '/Interaction/developmentcurve_decile_ratio_low.svg'),width = 14, height = 12, units = "cm")


# high
ggplot(data=plotdf.decile.low, aes(x=age, y=fit.avg, group=decile, color=decile))+
  geom_line(size=1.5, alpha=0.8, linetype="solid")+
  #paletteer::scale_color_paletteer_c("pals::ocean.matter", direction = -1, values=colorbarvalues.meanderiv2, oob = squish) +
  scale_color_distiller(type="seq", palette = "RdBu", direction = -1)+
  labs(x="Age (years)", y="SC strength (ratio)")+
  #scale_color_manual(values = rev(brewer.pal(6, "RdBu")))+
  theme_classic()+
  theme(axis.text=element_text(size=20, color="black"), 
        axis.title =element_text(size=20, color="black"),aspect.ratio = 0.8,
        plot.background=element_rect(fill="transparent"),legend.position = "none",
        panel.background=element_rect(fill="transparent"),
        plot.title = element_text(size=15, hjust = 0.5))
ggsave(paste0(FigureFolder, '/cognition/', Cogvar, '/Interaction/developmentcurve_decile_ratio_high.tiff'),width = 14, height = 12, units = "cm")
ggsave(paste0(FigureFolder, '/cognition/', Cogvar, '/Interaction/developmentcurve_decile_ratio_high.svg'),width = 14, height = 12, units = "cm")

```


