---
title: "HCPD_demography"
author: "Xiaoyu xu"
date: "5/13/2024"
output: html_document
---
This script extract the demographic and behavioural information together as a dataframe.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(tidyverse)
library(psych)
library(rjson)
library(openxlsx)
behaviorFolder <- '/Users/xuxiaoyu_work/Cuilab/open_dataset_information/HCP/HCPD_behavior'
sublistFolder <- '/Users/xuxiaoyu_work/Cuilab/open_dataset_information/HCP/HCPD_SC_info'

```

## 1. Participants with complete dMRI and normal anatomy

```{r complete_data}
HCPD_subcomp <-read.csv(paste0(sublistFolder, '/HCD_LS_2.0_subject_completeness.csv'))
HCPD_subcomp <- HCPD_subcomp[-1,]
nall <- nrow(HCPD_subcomp)
HCPD_subcomp[,c(8:21, 23:85)] <- lapply(HCPD_subcomp[,c(8:21, 23:85)], as.numeric)
HCPD_subcomp <- HCPD_subcomp %>% filter(dMRI_Compl==1 & str_detect(HCPD_subcomp$QC_Issue_Codes, "A")==0)
print(paste0(nall-nrow(HCPD_subcomp), " participants were removed due to incomplete dMRI and abnormal anatomy."))
subin <- HCPD_subcomp[,c("src_subject_id", "unrelated_subset", "interview_age", "sex")]

```

## 2. merge demographic information

handedness, race, fluid cognition

```{r merge_demo}
# handedness
hand <- read.csv(paste0(behaviorFolder, '/edinburgh_hand01.csv'), header=T)
hand <- hand[-1,]
hand[,] <- lapply(hand[,], as.factor)
hand$interview_age <- as.numeric(hand$interview_age)
item_over11 <- c("writing", "throwing", "scissors", "toothbrush", "knife_no_fork", "spoon", "broom", "match", "box", "foot")
item_under11 <- c("writing", "hammer","hand5", "throwing", "toothbrush", "spoon", "scissors", "hand_15_drink")

hand$right_number <- 0
hand$left_number <- 0
index_sub <- which(hand$interview_age >=11*12)
for (i in index_sub){
  for (item in item_over11){
    hand$right_number[i] <- hand$right_number[i] + 2*str_detect(hand[i,item], "right")+str_detect(hand[i,item], "spr")
    hand$left_number[i] <- hand$left_number[i] + 2*str_detect(hand[i,item], "left")+str_detect(hand[i,item], "spl")
  }
}
index_sub <- which(hand$interview_age <11*12)
for (i in index_sub){
  for (item in item_under11){
    hand$right_number[i] <- hand$right_number[i] + 2*str_detect(hand[i,item], "right")+str_detect(hand[i,item], "spr")
    hand$left_number[i] <- hand$left_number[i] + 2*str_detect(hand[i,item], "left")+str_detect(hand[i,item], "spl")
  }
}
hand <- hand %>% mutate(
  LQ = (right_number-left_number)*100 / (right_number+left_number)
)
summary(hand$LQ)
hand <- hand %>% mutate(
  handnessfactor = case_when(
    LQ >= 60 ~ 1, # right handed
    LQ <= -60 ~ 2, # left handed
    TRUE ~ 3 # mixed handed
  )
)
table(hand$handnessfactor)
subin <- subin %>% left_join(select(hand, c("src_subject_id", "LQ", "handnessfactor")), by="src_subject_id")

# race
demograph <- read.csv(paste0(behaviorFolder, '/socdem01.csv'), header = T);
demograph <- demograph[-1,]
demograph <- demograph %>% mutate(
  race_ethnicity = case_when(
    ethnicity=="Hispanic or Latino" ~ "Hispanic",
    ethnicity!="Hispanic or Latino" & race=="White" ~ "White",
    ethnicity!="Hispanic or Latino" & race=="Asian" ~ "Asian",
    ethnicity!="Hispanic or Latino" & race=="Black or African American" ~ "Black",
    ethnicity!="Hispanic or Latino" & race %in% c("Hawaiian or Pacific Islander", "More than one race") ~ "Other",
    TRUE ~ "Unknown"
  )
)
table(demograph$race_ethnicity)
subin <- subin %>% left_join(select(demograph, c("src_subject_id", "race_ethnicity")), by="src_subject_id")

# fluid cognition
cogcomp01 <- read.csv(paste0(behaviorFolder, '/cogcomp01.csv'));
cogcomp01 <- cogcomp01[-1, ]
cogvars <- c("nih_fluidcogcomp_unadjusted", "nih_fluidcogcomp_ageadjusted", "nih_crycogcomp_unadjusted", "nih_crycogcomp_ageadjusted", "nih_cogfuncogcomp_unadj", "nih_cogfuncogcomp_ageadj", "nih_eccogcomp_unadjusted", "nih_eccogcomp_ageadjusted", "nih_totalcogcomp_unadjusted", "nih_totalcogcomp_ageadjusted")
cogcomp01[,cogvars] <- lapply(cogcomp01[,cogvars], as.numeric)
subin <- subin %>% left_join(select(cogcomp01, c("src_subject_id", cogvars)), by="src_subject_id")

# siteID
ndar_subject01 <- read.csv(paste0(behaviorFolder, '/ndar_subject01.csv'), header = T);
ndar_subject01 <- ndar_subject01[-1,]
subin <- subin %>% left_join(select(ndar_subject01,c("src_subject_id", "site")), by="src_subject_id")

```

## 3. merge processing info

mean FD

```{r add_meanFD}
qcpath <- "/Users/xuxiaoyu_work/Cuilab/open_dataset_information/HCP/SCmat/qcjson"
subin$mean_fd <- NA
for (i in 1:nrow(subin)){
  subID <- subin$src_subject_id[i]
  qcjson.tmp <- fromJSON(file=paste0(qcpath, "/sub-", subID, ".json"))
  meanFD <- qcjson.tmp$subjects[[1]]$mean_fd
  subin$mean_fd[i] <- meanFD
}
summary(subin$mean_fd)
subin$interview_age <- as.numeric(subin$interview_age)
subin$age <- subin$interview_age / 12
subin <- dplyr::rename(subin, subID="src_subject_id")
write.csv(subin, "/Users/xuxiaoyu_work/Cuilab/open_dataset_information/HCP/HCPD_behavior/HCPD_demo_behav.csv", row.names = F)
```
## SES
```{r SES}
socdem01 <- read.csv("/Users/xuxiaoyu_work/Cuilab/open_dataset_information/HCP/HCPD_behavior/socdem01.csv")
socdem01 <- socdem01[-1, ]
subin <- subin %>% left_join(select(socdem01, c("src_subject_id", "interview_date", "household_number_in_house", "annual_fam_inc")), join_by(subID==src_subject_id))
reference_data <- data.frame(familysize = c(1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12, 1,2,3,4,5,6,7,8,9,10,11,12), povertyline = c(12140,16460,20780,25100,29420,33740,38060,42380, 46700,51020,	55340,	59660, 12060,16240,20420,24600,28780,32960,37140,41320, 45500,	49680,	53860,	58040,12490,	16910,	21330,	25750,	30170,	34590,	39010,	43430,	47850,	52270,	56690,	61110),Year = c(rep(2018,12), rep(2017,12), rep(2019,12)))
subin$interviewyear<-year(subin$interview_date)
subin <- merge(subin, reference_data,by.x = c("interviewyear", "household_number_in_house"),by.y = c("Year", "familysize"), all.x = TRUE)
subin$annual_fam_inc <- as.numeric(subin$annual_fam_inc)
subin$income.adj<-subin$annual_fam_inc / subin$povertyline
subin$income.adj[subin$income.adj < 0] <- NA
summary(subin$income.adj)
write.csv(subin, "/Users/xuxiaoyu_work/Cuilab/open_dataset_information/HCP/HCPD_behavior/HCPD_demo_behav.csv", row.names = F)

```
## ICV
```{r ICV}
ICV <- read.csv(paste0(behaviorFolder, "/ICV.csv"))
ICV$subID <- str_split_i(ICV$subID, "sub-",2)
subin <- merge(subin, ICV, by="subID")
write.csv(subin, "/Users/xuxiaoyu_work/Cuilab/open_dataset_information/HCP/HCPD_behavior/HCPD_demo_behav.csv", row.names = F)

```

